GET http://localhost:3001

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

GET https://billowing-meadow-6707.fly.dev/api/persons

###

GET http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Babajide Ibiayo",
    "number": "2348096396832"
}

###

PUT http://localhost:3001/api/persons/2

###

DELETE http://localhost:3001/api/persons/3